import "oaidl.idl";

[
    object,
    uuid(12345678-1234-1234-1234-123456789ABC),
    dual,
    helpstring("ISampleInterface Interface"),
    pointer_default(unique)
]
interface ISampleInterface : IDispatch {
    HRESULT SampleMethod([in] BSTR input, [out, retval] BSTR* output);
};
